version: "3.4"

x-common-variables: &common-variables
  MYSQL_ROOT_PASSWORD: root
  MYSQL_HOST: localhost
  MYSQL_ROOT_HOST: '%'
  MYSQL_DATABASE: docker_app_web
  REACT_APP_SERVER_PORT: 8000

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      <<: *common-variables
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    expose:
      - "3306"
    ports:
      - 3306:3306
    volumes:
      - ./PC2_db/init.sql:/docker-entrypoint-initdb.d/init.sql
  phpmyadmin:
    depends_on:
      - mysql-db
    image: phpmyadmin/phpmyadmin
    container_name: phpadmin_container
    environment:
      PMA_HOST: mysql-db
    links:
      - mysql-db:mysql-db
    ports:
      - 8080:80
    restart: always
  server:
    build: ./PC2_server
    container_name: node_server_container
    depends_on:
      - mysql-db
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql_container
    ports:
      - 8000:8000
    volumes:
      - ./PC2_server:/app
    links:
      - mysql-db
    command: ["wait-for-it", "mysql-db:3306", "--", "node",  "index.js"]
  client:
    build: ./PC2_frontend/PC2_front
    container_name: client_container
    environment:
      <<: *common-variables
      NODE_PATH: src
    ports:
      - 3000:3000
    volumes:
      - ./PC2_frontend/PC2_front/src:/app/src
    links:
      - server
    command: npm start